// No automatic generation: we don't want to depend on fs, as we want to keep this universal
// ls *-*.json | while read line; do printf "\"`printf $line | cut -d '.' -f1`\",\n"; done

var languages = [
	"ar-AR",
	"bg-BG",
	"ca-ES",
	"cs-CZ",
	"da-DK",
	"de-DE",
	"el-GR",
	"en-US",
	"eo-EO",
	"es-ES",
	"eu-ES",
	"fa-IR",
	"fi-FI",
	"fr-FR",
	"he-IL",
	"hi-IN",
	"hr-HR",
	"hu-HU",
	"id-ID",
	"it-IT",
	"ja-JP",
	"ko-KR",
	"lt-LT",
	"mk-MK",
	"my-BM",
	"nb-NO",
	"ne-NP",
	"nl-NL",
	"nn-NO",
	"pa-IN",
	"pl-PL",
	"pt-BR",
	"pt-PT",
	"ro-RO",
	"ru-RU",
	"sl-SL",
	"sr-RS",
	"sv-SE",
	"sk-SK",
	"te-IN",
	"tr-TR",
	"uk-UA",
	"ur-PK",
	"vi-VN",
	"zh-CN",
	"zh-HK",
	"zh-TW",
	"bn-BD",
	"tl-TM",
	"et-EE"
];

module.exports = function () {
	return {
    "ar-AR": require("./ar-AR.json"),
    "bg-BG": require("./bg-BG.json"),
    "ca-ES": require("./ca-ES.json"),
    "cs-CZ": require("./cs-CZ.json"),
    "da-DK": require("./da-DK.json"),
    "de-DE": require("./de-DE.json"),
    "el-GR": require("./el-GR.json"),
    "en-US": require("./en-US.json"),
    "eo-EO": require("./eo-EO.json"),
    "es-ES": require("./es-ES.json"),
    "eu-ES": require("./eu-ES.json"),
    "fa-IR": require("./fa-IR.json"),
    "fi-FI": require("./fi-FI.json"),
    "fr-FR": require("./fr-FR.json"),
    "he-IL": require("./he-IL.json"),
    "hi-IN": require("./hi-IN.json"),
    "hr-HR": require("./hr-HR.json"),
    "hu-HU": require("./hu-HU.json"),
    "id-ID": require("./id-ID.json"),
    "it-IT": require("./it-IT.json"),
    "ja-JP": require("./ja-JP.json"),
    "ko-KR": require("./ko-KR.json"),
	'lt-LT': require('./lt-LT.json'),
    "mk-MK": require("./mk-MK.json"),
    "my-BM": require("./my-BM.json"),
    "nb-NO": require("./nb-NO.json"),
    "ne-NP": require("./ne-NP.json"),
    "nl-NL": require("./nl-NL.json"),
    "nn-NO": require("./nn-NO.json"),
    "pa-IN": require("./pa-IN.json"),
    "pl-PL": require("./pl-PL.json"),
    "pt-BR": require("./pt-BR.json"),
    "pt-PT": require("./pt-PT.json"),
    "ro-RO": require("./ro-RO.json"),
    "ru-RU": require("./ru-RU.json"),
    "sl-SL": require("./sl-SL.json"),
    "sr-RS": require("./sr-RS.json"),
    "sv-SE": require("./sv-SE.json"),
    "sk-SK": require("./sk-SK.json"),
    "te-IN": require("./te-IN.json"),
    "tr-TR": require("./tr-TR.json"),
    "uk-UA": require("./uk-UA.json"),
    "ur-PK": require("./ur-PK.json"),
    "vi-VN": require("./vi-VN.json"),
    "zh-CN": require("./zh-CN.json"),
    "zh-HK": require("./zh-HK.json"),
    "zh-TW": require("./zh-TW.json"),
    "bn-BD": require("./bn-BD.json"),
	"tl-TM": require("./tl-TM.json"),	
    "et-EE": require("./et-EE.json"),
  };
};

module.exports.all = languages;
